package applicationProcess;

public enum ApplicationProcessStatus {
    NEW,
    HOLD,
    FIRSTSTEPSENT,
    SECONDSTEPVERIFIEDPOSITIVE,
    SECONDSTEPVERIFIEDNEGATIVE,
    SECONDSTEPTOCORRECT,
    THIRDSTEPMEETINGSCHEDULED,
    THIRDSTEPMEETINGUNSCHEDULED,
    THIRDSTEPMEETINGFINISHED,
    ADOPTED;
}
